name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Install dependencies
              run: |
                  pip install sphinx

            - name: Build Sphinx documentation
              run: |
                  cd doc
                  mkdir -p build
                  sphinx-build source build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: doc/build
                  force_orphan: true
